### ISSUE TITLE
Ctrl-D bug

### ISSUE THREAD

**Issue by aritra1911** [CodeOn-ArK/RawTerm_CPP#7]
I have a habit of getting out of terminal windows and shells by pressing Ctrl-D which essentially is just interpreted as EOF. But when I do this accidentally here, it crashes and my terminal starts to look like hell. Here's a picture of the hell I'm referring to:
![Screenshot_2021-03-29_11-05-51](https://user-images.githubusercontent.com/42066518/112791642-99c4f400-907f-11eb-842e-afa5ea4866b2.png)
There's no way out of this other than Ctrl-C, terminating the application.

**Comment by CodeOn-ArK** [comment]
Issue will be resolved soon

**Comment by CodeOn-ArK** [comment]
Your issue has been resolved in the latest commit.
Use ```EXIT Console ``` option in Menu
GO to Menu by Entering ```__MENU```

**Comment by aritra1911** [comment]
Issue still persists!
Here, this hell still appears when I press Ctrl-D.
![1617021495_1808_29 03 2021_1920x1080](https://user-images.githubusercontent.com/42066518/112837773-ecbb9d00-90b9-11eb-81e5-99878305fee0.png)

**Comment by aritra1911** [comment]
Commit ac90df5 fixed this issue and it's working as of now, but you must provide enough information in order to reproduce the issue in case you think this issue is not completely fixed.

Warning! Don't compile the latest commit on `test` branch as of now. It broke a ton of things.

**Comment by CodeOn-ArK** [comment]
However even after resolving the problem it gave this and it slows down input process i.e. I have to press enter twice to make it take input.
![Screenshot_6](https://user-images.githubusercontent.com/70703857/112980152-256d7c00-9177-11eb-8856-5abbbad09ba5.png)

**Comment by CodeOn-ArK** [comment]
send a PR to my latest commit in test branch, then we will discuss the issue

**Comment by CodeOn-ArK** [comment]
Issue fixed
